general:
steps:
 gctsDeploy:
 host: "https://hcluks4hana.hcldigilabs.com:8001/"
 client: "200"
 abapCredentialsId: "<credentials_saved_in_jenkins>"
 repository: "<repo_name>"
 remoteRepositoryURL: "<repository_url>"
 role: "SOURCE"
 vSID: "<the_vsid_assigned_to_you>"
 verbose: true
 type: "GITHUB"
 rollback: false
