general:
steps:
 gctsDeploy:
 host: "https://hcluks4hana.hcldigilabs.com:8001/"
 client: "200"
 abapCredentialsId: "SAPCredsForN09200"
 repository: "N09_REPO002"
 remoteRepositoryURL: "https://github.com/SaurabhCHCLTech/N09_REPO002.git"
 role: "SOURCE"
 vSID: "YSC"
 verbose: true
 type: "GITHUB"
 rollback: false
